import { type NextPage } from "next";
import Head from "next/head";
import { NavLayout } from "../client/layouts/NavLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLayout>
        <main className="flex justify-around py-5">
          <button>Create a Line</button>
          <button>Join a Line</button>
        </main>
      </NavLayout>
    </>
  );
};

export default Home;
