import { type NextPage } from "next";
import Head from "next/head";
import { NavLayout } from "../client/layouts/NavLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLayout>
        <main className="py-5"></main>
      </NavLayout>
    </>
  );
};

export default Home;
